server:
  port: 31020
  compression:
    enabled: true  # 开启全局响应压缩
    mime-types: application/json,text/plain,text/html,text/xml,application/javascript,text/css # 指定对 JSON 和 TXT 进行压缩
    min-response-size: 2048 # 只有当返回值大于 2KB 时才进行压缩，节省 CPU

spring:
  application:
    name: Gingest
  threads:
    virtual:
      enabled: true

# 自定义 GitLab 配置
gitlab:
  url: "http://192.168.4.166/"
  token: "这里填入gitlab的访问token"


# Gingest 过滤规则配置
gingest:
  ignore:
    extensions:
      - ".png"
      - ".jpg"
      - ".jpeg"
      - ".gif"
      - ".ico"
      - ".pdf"
      - ".zip"
      - ".tar"
      - ".gz"
      - ".jar"
      - ".class"
      - ".exe"
      - ".xml"
      - ".node"
      - ".dll"
      - ".so"
      - ".dylib"
      - ".woff"
      - ".woff2"
      - ".ttf"
      - ".eot"
      - ".mp4"
      - ".mp3"
      - ".svg"
      - ".properties"
      - ".cmd"
      - ".gitignore"
      - ".config"
      - ".iml"
      - ".map"
      - ".sql"
      - ".bak"
      - ".log"
      - ".out"
      - ".min.js"
      - ".min.css"
    directories:
      - "node_modules"
      - ".git"
      - "target"
      - ".idea"
      - "build"
      - "dist"
    file-names:
      - "package-lock.json"
      - "yarn.lock"
      - "pnpm-lock.yaml"
